// <auto-generated />
namespace MiContact.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmailAddBasicInfoTbale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmailAddBasicInfoTbale));
        
        string IMigrationMetadata.Id
        {
            get { return "201702250543417_EmailAddBasicInfoTbale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
